server:
  port: 3434

spring:
  application:
    name: GroceryFinderV2
  data:
    mongodb:
      uri: mongodb://localhost:27017/grocery_finder_db
    redis:
      host: localhost
      port: 6379
      timeout: 6000ms

  mail:
    username: nmt.m10.2862001@gmail.com
    password: uxtbnerqqbgafmop
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connection-timeout: 5000
          write-timeout: 5000

jwt:
  secret-key: 873f47869c454e32b09a992174b280631234ab77720
  refresh-secret-key: 873f47869c454e32b09a992174b880731234ab77720
  access:
    token:
      expiration: 3600  # 1 hour in seconds
  refresh:
    jwt:
      access:
        token:
          expiration: 86400  # 24 hours in seconds

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /v1/actuator
  endpoint:
    health:
      status:
        http-mapping:
          down: 500
      show-details: always
